### ISSUE TITLE
Question about RGFW compiler errors

### ISSUE THREAD

**Issue by ColleagueRiley** [Code-Nycticebus/claymore#10]
In the RGFW header file, you say,

```
Disclaimer: This code has been altered to fix some compiler errors.
 	- Code-Nycticebus
```

Could you the compiler errors so I can fix them in the  RGFW repo? 

I assume these errors come from compiling RGFW with MSVC, as I've not done much testing with MSVC.

**Comment by Code-Nycticebus** [comment]
I'm planning on fixing this and creating a pull request soon (actually this Saturday 25.05.2024).

Actually everything is just a warning. But i really like to enable `-Werror` when creating builds.

- Some warnings come when compiling with `gcc-mingw` compiler on windows. (Just the `WIN32` and `WIN64` macros are already defined by the compiler). 
- Others are when enabling extra flags like `-Wstrict-prototypes` and `-Wextra` that i like to enable on all my builds. The problem i have right now is i can't test the vulkan part of the code for now.


I will fix and test the first warning since that will be easy. 
The second one is a little more involved so let me know if you even want that fixed.

**Comment by ColleagueRiley** [comment]
I believe I already fixed the first problem. I’ll look into the others later today and I’ll probably be able to fix them all before Saturday. I’ll make sure the fixes apply to all the OSes and Graphics APIs.

Why can't you test Vulkan? Is that because of an issue with RGFW or an issue on your end?

**Comment by Code-Nycticebus** [comment]
I just don't have a vulkan development setup right now.

as for the other problems, i can work around the `-Wextra` warnings since the most warnings come from the implementation. I can precompile the header without warnings enabled (like i did in the project). 

The `-Wstrict-prototype` is kind of a problem for me since i include the header in my source files. 
I just had to change `RGFW_Error(void);` and  `RGFW_getMaxGLVersion(void);` to get it working but i also saw right now that in some vulkan functions you'd have to change that aswell.
 
I really like the project btw.

**Comment by ColleagueRiley** [comment]
Thank you so much! I think I'll be able to get the problems fixed before the end of today :)

**Comment by Code-Nycticebus** [comment]
Looking forward to it. 

Now i have to do new plans for the weekend :)

**Comment by ColleagueRiley** [comment]
@Code-Nycticebus These should all be fixed with the latest commit.

**Comment by Code-Nycticebus** [comment]
should work. 

thank you
