### ISSUE TITLE
pybuildc alternative

### ISSUE THREAD

**Issue by ColleagueRiley** [Code-Nycticebus/claymore#13]
I'm struggling to properly setup pybuildc. I think it would be nice if there was a alternative to pybuildc included (such as makefile or make).

**Comment by Code-Nycticebus** [comment]
I’m open to alternative build systems for claymore. However, I don’t currently have the skills to implement a makefile myself. 

If you or anyone is interested in contributing or has expertise in this area, please feel free to contribute.

**Comment by Code-Nycticebus** [comment]
How about i go for the [nobuild](https://github.com/tsoding/nobuild) approach. 

It's not finished yet just a draft.
Checkout the [build](https://github.com/Code-Nycticebus/claymore/tree/build) branch.
read the [readme](https://github.com/Code-Nycticebus/claymore/blob/build/build/readme.md).


TODO:
- [ ] Build claymore as a library
- [ ] Cross Platform (currently only linux)
- [ ] debug/release

**Comment by alexlnkp** [comment]
> How about i go for the [nobuild](https://github.com/tsoding/nobuild) approach.
> 
> It's not finished yet just a draft.
> 
> TODO:
> 
>     * [x]  Build claymore as a library
> 
>     * [x]  Cross Platform (currently only linux)
> 
>     * [ ]  debug/release

NoBuild sounds like a great alternative, however i think CMake will be more versatile and potentially easier to use

**Comment by Code-Nycticebus** [comment]
I’ve thought about it too since it can make Visual Studio integration easier if people want to contribute with it. But i don't personally use VS or CMake, so integrating them would be a bit tough for me..

So again I'm open to any kind of build system but i would need help integrating them.

The project is very easy to build with any kind of build system thanks to [RGFW](https://github.com/ColleagueRiley/RGFW) and all the other header-only libraries.

**Comment by ColleagueRiley** [comment]
Got it to build with no-build just fine
